apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-env-file
  namespace: muchtodo
data:
  .env: |
    PORT=8080
    MONGO_URI=mongodb://root:example@mongodb-service:27017/much_todo_db?authSource=admin&replicaSet=rs0&directConnection=true
    DB_NAME=much_todo_db
    JWT_SECRET_KEY=your-super-secret-key-that-is-long-and-random
    JWT_EXPIRATION_HOURS=72
    ENABLE_CACHE=false
    LOG_LEVEL=INFO
    LOG_FORMAT=json
