apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: muchtodo
type: Opaque
stringData:
  JWT_SECRET_KEY: your-super-secret-key-that-is-long-and-random
  MONGO_URI: mongodb://root:example@mongodb-service:27017/much_todo_db?authSource=admin&replicaSet=rs0&directConnection=true
